// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/lists": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Свои и общие списки текущего пользователя со счётчиками, ролью и участниками. Список по умолчанию идёт первым и создаётся автоматически. Администратор может передать user_id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lists"
                ],
                "summary": "Мои списки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Чьи списки показать (только для администратора)",
                        "name": "user_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_lists_transport_http.ListSummaryDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lists"
                ],
                "summary": "Создать список",
                "parameters": [
                    {
                        "description": "Новый список",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.CreateListRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.ListDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/join": {
            "post": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Код берётся из ссылки t.me/\u003cбот\u003e?startapp=join_\u003cкод\u003e. Повторное вступление ничего не меняет",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lists"
                ],
                "summary": "Вступить в список по приглашению",
                "parameters": [
                    {
                        "description": "Код приглашения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.JoinListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.ListDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Приглашение не найдено или выключено",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/{id}": {
            "delete": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Удаляет список вместе со всеми его задачами, только владелец (участнику — 403). Список по умолчанию удалить нельзя (409)",
                "tags": [
                    "lists"
                ],
                "summary": "Удалить список",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID списка",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Список удалён"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Список по умолчанию",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Название и цвет, только владелец (участнику — 403). Необязательное поле 'version' защищает от одновременного изменения (409)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lists"
                ],
                "summary": "Изменить список",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID списка",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Изменения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.PatchListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.ListDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/{id}/invite": {
            "post": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Выдаёт новый код приглашения (прежняя ссылка перестаёт работать). Только владелец. Список по умолчанию расшарить нельзя (409). invite_link заполняется, если задан AUTH_TELEGRAM_BOT_USERNAME",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lists"
                ],
                "summary": "Ссылка-приглашение в список",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID списка",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.ListDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Не владелец",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Список по умолчанию",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Ссылка перестаёт работать, уже вступившие остаются. Только владелец",
                "tags": [
                    "lists"
                ],
                "summary": "Выключить приглашение",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID списка",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Приглашение выключено"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Не владелец",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/{id}/members/{user_id}": {
            "delete": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Участник может удалить себя (выйти), владелец — любого участника. Владелец выйти не может (409)",
                "tags": [
                    "lists"
                ],
                "summary": "Исключить участника или выйти из списка",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID списка",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID участника",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Участник удалён из списка"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Не владелец",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Владелец не может выйти",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lists/{id}/notifications": {
            "put": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Личный переключатель владельца или участника: бот пишет, когда другие добавляют или выполняют задачи. По умолчанию включён",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "lists"
                ],
                "summary": "Сообщать об изменениях в списке",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID списка",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Включить или выключить",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_lists_transport_http.SetNotifyChangesRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Сохранено"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Пользователь, от имени которого выполняется запрос. Создаётся автоматически при первом входе через Telegram",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Текущий пользователь",
                "responses": {
                    "200": {
                        "description": "Текущий пользователь",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.GetMeResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/statistics": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Получение статистики по задачам с опциональной фильтрацией по user_id и/или временному промежутку",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statistics"
                ],
                "summary": "Получение статистики",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Фильтрация статистики по конкретному пользователю",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Начало промежутка рассмотрения статистики (включительно), формат: YYYY-MM-DD",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Конец промежутка рассмотрения статистики (не включительно), формат: YYYY-MM-DD",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение",
                        "schema": {
                            "$ref": "#/definitions/internal_features_statistics_transport_http.GetStatisticsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Сначала невыполненные, по ближайшему сроку; без срока — в конце",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Список задач",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Фильтрация задач по ID автора (только для администратора)",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Задачи одного списка",
                        "name": "list_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Размер страницы с задачами (по умолчанию 50, максимум 500)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение страницы с задачами",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка задач",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_tasks_transport_http.TaskDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Создать новую задачу в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Создать задачу",
                "parameters": [
                    {
                        "description": "CreateTask тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.CreateTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешно созданная задача",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.CreateTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Автор не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Получение конкретной задачи по ее ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Получение задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID получаемой задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Задача успешно найдена",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.GetTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Удаление существующей задачи по ее ID",
                "tags": [
                    "tasks"
                ],
                "summary": "Удаление задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID удаляемой задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление задачи"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Обновляет информацию об уже существующей в системе задаче\n### Логика обновления полей (Three-state logic):\n1. **Поле не передано**: 'description' игнорируется, значение в БД не меняется\n2. **Явно передано значение**: '\"description\": \"Утром в 06:30 выйти на прогулку с Бобиком\"'\n3. **Явно передан null**: '\"description\": null' - очищает поле в БД (set to NULL)\nОграничения: 'title' и 'completed' не могут быть выставлены как null\nНеобязательное поле 'version' — версия, которую видел клиент; при расхождении с текущей вернётся 409\nВыполнение повторяющейся задачи создаёт следующую с новым сроком, у выполненной повтор снимается",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Обновить задачу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID изменяемой задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchTask тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.PatchTaskRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно изменённая задача",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.PatchTaskResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/items": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Пункты задачи по порядку. Доступ — как у задачи",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Чеклист задачи",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_tasks_transport_http.TaskItemDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Пункт встаёт в конец чеклиста. У задачи не больше 100 пунктов (409)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Добавить пункт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый пункт",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.CreateTaskItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.TaskItemDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Слишком много пунктов",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks/{id}/items/{item_id}": {
            "delete": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Удалить пункт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID пункта",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Пункт удалён"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Текст и отметка. Необязательное поле 'version' защищает от одновременного изменения (409)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Изменить пункт",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID задачи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID пункта",
                        "name": "item_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Изменения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.PatchTaskItemRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.TaskItemDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Просмотр списка пользователей с опциональной пагинацией",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Список пользователей",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Размер страницы с пользователями (по умолчанию 50, максимум 500)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение страницы с пользователями",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение списка пользователей",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_features_users_transport_http.UserDTOResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Только для администратора",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Создать нового пользователя в системе",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Создать пользователя",
                "parameters": [
                    {
                        "description": "CreateUser тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешно созданный пользователь",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Только для администратора",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Получение конкретного пользователя по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получение пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID получаемого пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь успешно найден",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.GetUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Удаление существующего пользователя по его ID",
                "tags": [
                    "users"
                ],
                "summary": "Удаление пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID удаляемого пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Успешное удаление пользователя"
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Только для администратора",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "У пользователя есть задачи",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "TelegramInitData": []
                    }
                ],
                "description": "Изменение информации об уже существующем в системе пользователе.\nНеобязательное поле 'version' — версия, которую видел клиент; при расхождении с текущей вернётся 409",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Изменение пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID изменяемого пользователя",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PatchUser тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешно измененный пользователь",
                        "schema": {
                            "$ref": "#/definitions/internal_features_users_transport_http.PatchUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Нет или неверные данные Telegram",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_dadqeds_todoapp_internal_core_transport_http_response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "full error text"
                },
                "message": {
                    "type": "string",
                    "example": "short human-readable message"
                }
            }
        },
        "github_com_dadqeds_todoapp_internal_core_transport_http_types.Nullable-internal_features_tasks_transport_http_RepeatDTO": {
            "type": "object",
            "properties": {
                "set": {
                    "type": "boolean"
                },
                "value": {
                    "$ref": "#/definitions/internal_features_tasks_transport_http.RepeatDTO"
                }
            }
        },
        "internal_features_lists_transport_http.CreateListRequest": {
            "type": "object",
            "required": [
                "color",
                "title"
            ],
            "properties": {
                "color": {
                    "type": "string",
                    "enum": [
                        "green",
                        "violet",
                        "coral",
                        "blue",
                        "pink",
                        "amber"
                    ],
                    "example": "green"
                },
                "title": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1,
                    "example": "Дом"
                }
            }
        },
        "internal_features_lists_transport_http.JoinListRequest": {
            "type": "object",
            "required": [
                "code"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 8,
                    "example": "pQ3x_Zr8k1LmN0aB"
                }
            }
        },
        "internal_features_lists_transport_http.ListDTOResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "enum": [
                        "green",
                        "violet",
                        "coral",
                        "blue",
                        "pink",
                        "amber"
                    ],
                    "example": "green"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 3
                },
                "invite_code": {
                    "description": "Только для владельца: код и ссылка приглашения, null — приглашение выключено.",
                    "type": "string",
                    "example": "pQ3x_Zr8k1LmN0aB"
                },
                "invite_link": {
                    "type": "string",
                    "example": "https://t.me/my_todo_bot?startapp=join_pQ3x_Zr8k1LmN0aB"
                },
                "is_default": {
                    "type": "boolean",
                    "example": false
                },
                "owner_user_id": {
                    "type": "integer",
                    "example": 1
                },
                "title": {
                    "type": "string",
                    "example": "Дом"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_lists_transport_http.ListMemberDTO": {
            "type": "object",
            "properties": {
                "full_name": {
                    "type": "string",
                    "example": "Анна"
                },
                "joined_at": {
                    "type": "string"
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "owner",
                        "member"
                    ],
                    "example": "member"
                },
                "user_id": {
                    "type": "integer",
                    "example": 7
                }
            }
        },
        "internal_features_lists_transport_http.ListSummaryDTOResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "enum": [
                        "green",
                        "violet",
                        "coral",
                        "blue",
                        "pink",
                        "amber"
                    ],
                    "example": "green"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer",
                    "example": 3
                },
                "invite_code": {
                    "description": "Только для владельца: код и ссылка приглашения, null — приглашение выключено.",
                    "type": "string",
                    "example": "pQ3x_Zr8k1LmN0aB"
                },
                "invite_link": {
                    "type": "string",
                    "example": "https://t.me/my_todo_bot?startapp=join_pQ3x_Zr8k1LmN0aB"
                },
                "is_default": {
                    "type": "boolean",
                    "example": false
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_features_lists_transport_http.ListMemberDTO"
                    }
                },
                "notify_changes": {
                    "description": "Сообщать ли текущему пользователю об изменениях в этом списке.",
                    "type": "boolean",
                    "example": true
                },
                "open_tasks": {
                    "type": "integer",
                    "example": 3
                },
                "owner_user_id": {
                    "type": "integer",
                    "example": 1
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "owner",
                        "member"
                    ],
                    "example": "owner"
                },
                "title": {
                    "type": "string",
                    "example": "Дом"
                },
                "total_tasks": {
                    "type": "integer",
                    "example": 5
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_lists_transport_http.PatchListRequest": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "amber"
                },
                "title": {
                    "type": "string",
                    "example": "Дача"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_lists_transport_http.SetNotifyChangesRequest": {
            "type": "object",
            "required": [
                "notify_changes"
            ],
            "properties": {
                "notify_changes": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "internal_features_statistics_transport_http.GetStatisticsResponse": {
            "type": "object",
            "properties": {
                "lists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_features_statistics_transport_http.ListStatisticsResponse"
                    }
                },
                "tasks_average_completion_seconds": {
                    "description": "Секунды — чтобы фронт мог показать «1 день 4 ч», а не разбирать строку Go.",
                    "type": "integer",
                    "example": 90
                },
                "tasks_average_completion_time": {
                    "type": "string",
                    "example": "1m30s"
                },
                "tasks_completed": {
                    "type": "integer",
                    "example": 10
                },
                "tasks_completed_on_time": {
                    "type": "integer",
                    "example": 5
                },
                "tasks_completed_rate": {
                    "type": "number",
                    "example": 20
                },
                "tasks_completed_with_due": {
                    "type": "integer",
                    "example": 6
                },
                "tasks_created": {
                    "type": "integer",
                    "example": 50
                },
                "tasks_on_time_rate": {
                    "type": "number",
                    "example": 83.3
                }
            }
        },
        "internal_features_statistics_transport_http.ListStatisticsResponse": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "green"
                },
                "list_id": {
                    "type": "integer",
                    "example": 3
                },
                "tasks_completed": {
                    "type": "integer",
                    "example": 7
                },
                "tasks_created": {
                    "type": "integer",
                    "example": 9
                },
                "title": {
                    "type": "string",
                    "example": "Дом"
                }
            }
        },
        "internal_features_tasks_transport_http.CreateTaskItemRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "title": {
                    "type": "string",
                    "maxLength": 200,
                    "minLength": 1,
                    "example": "Молоко"
                }
            }
        },
        "internal_features_tasks_transport_http.CreateTaskRequest": {
            "type": "object",
            "required": [
                "title"
            ],
            "properties": {
                "author_user_id": {
                    "description": "Учитывается только для администратора, остальным автором ставится текущий пользователь.",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1
                },
                "description": {
                    "type": "string",
                    "maxLength": 1000,
                    "minLength": 1,
                    "example": "2 литра, 3.2%"
                },
                "due_all_day": {
                    "type": "boolean",
                    "example": false
                },
                "due_at": {
                    "description": "Срок с часовым поясом. Для срока «на весь день» — конец дня по времени пользователя.",
                    "type": "string",
                    "example": "2026-10-05T18:00:00+03:00"
                },
                "list_id": {
                    "description": "Не указан — список по умолчанию автора.",
                    "type": "integer",
                    "minimum": 1,
                    "example": 3
                },
                "remind_before_minutes": {
                    "description": "0 — в срок, 15, 60, 1440 — за день; требует срока.",
                    "type": "integer",
                    "example": 15
                },
                "repeat": {
                    "description": "Повтор требует срока.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/internal_features_tasks_transport_http.RepeatDTO"
                        }
                    ]
                },
                "title": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Купить молоко"
                }
            }
        },
        "internal_features_tasks_transport_http.CreateTaskResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "type": "integer"
                },
                "completed": {
                    "type": "boolean"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_all_day": {
                    "type": "boolean"
                },
                "due_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items_done": {
                    "type": "integer",
                    "example": 3
                },
                "items_total": {
                    "description": "Пункты чеклиста: всего и отмеченных.",
                    "type": "integer",
                    "example": 7
                },
                "list_id": {
                    "type": "integer"
                },
                "remind_before_minutes": {
                    "description": "За сколько минут до срока напомнить: 0, 15, 60, 1440; null — без напоминания.",
                    "type": "integer",
                    "example": 15
                },
                "repeat": {
                    "$ref": "#/definitions/internal_features_tasks_transport_http.RepeatDTO"
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_features_tasks_transport_http.GetTaskResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "type": "integer"
                },
                "completed": {
                    "type": "boolean"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_all_day": {
                    "type": "boolean"
                },
                "due_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items_done": {
                    "type": "integer",
                    "example": 3
                },
                "items_total": {
                    "description": "Пункты чеклиста: всего и отмеченных.",
                    "type": "integer",
                    "example": 7
                },
                "list_id": {
                    "type": "integer"
                },
                "remind_before_minutes": {
                    "description": "За сколько минут до срока напомнить: 0, 15, 60, 1440; null — без напоминания.",
                    "type": "integer",
                    "example": 15
                },
                "repeat": {
                    "$ref": "#/definitions/internal_features_tasks_transport_http.RepeatDTO"
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_features_tasks_transport_http.PatchTaskItemRequest": {
            "type": "object",
            "properties": {
                "done": {
                    "type": "boolean",
                    "example": true
                },
                "title": {
                    "type": "string",
                    "example": "Молоко 3.2%"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_tasks_transport_http.PatchTaskRequest": {
            "type": "object",
            "properties": {
                "completed": {
                    "type": "boolean",
                    "example": true
                },
                "description": {
                    "type": "string",
                    "example": "2 литра"
                },
                "due_all_day": {
                    "type": "boolean",
                    "example": false
                },
                "due_at": {
                    "description": "null снимает срок",
                    "type": "string",
                    "example": "2026-10-06T10:00:00+03:00"
                },
                "list_id": {
                    "type": "integer",
                    "example": 3
                },
                "remind_before_minutes": {
                    "description": "null выключает напоминание",
                    "type": "integer",
                    "example": 60
                },
                "repeat": {
                    "description": "null выключает повтор",
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_dadqeds_todoapp_internal_core_transport_http_types.Nullable-internal_features_tasks_transport_http_RepeatDTO"
                        }
                    ]
                },
                "title": {
                    "type": "string",
                    "example": "Купить молоко"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_tasks_transport_http.PatchTaskResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "type": "integer"
                },
                "completed": {
                    "type": "boolean"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_all_day": {
                    "type": "boolean"
                },
                "due_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items_done": {
                    "type": "integer",
                    "example": 3
                },
                "items_total": {
                    "description": "Пункты чеклиста: всего и отмеченных.",
                    "type": "integer",
                    "example": 7
                },
                "list_id": {
                    "type": "integer"
                },
                "remind_before_minutes": {
                    "description": "За сколько минут до срока напомнить: 0, 15, 60, 1440; null — без напоминания.",
                    "type": "integer",
                    "example": 15
                },
                "repeat": {
                    "$ref": "#/definitions/internal_features_tasks_transport_http.RepeatDTO"
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_features_tasks_transport_http.RepeatDTO": {
            "type": "object",
            "properties": {
                "kind": {
                    "type": "string",
                    "enum": [
                        "daily",
                        "weekly",
                        "monthly",
                        "yearly"
                    ],
                    "example": "weekly"
                },
                "weekdays": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        4
                    ]
                }
            }
        },
        "internal_features_tasks_transport_http.TaskDTOResponse": {
            "type": "object",
            "properties": {
                "author_user_id": {
                    "type": "integer"
                },
                "completed": {
                    "type": "boolean"
                },
                "completed_at": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "due_all_day": {
                    "type": "boolean"
                },
                "due_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items_done": {
                    "type": "integer",
                    "example": 3
                },
                "items_total": {
                    "description": "Пункты чеклиста: всего и отмеченных.",
                    "type": "integer",
                    "example": 7
                },
                "list_id": {
                    "type": "integer"
                },
                "remind_before_minutes": {
                    "description": "За сколько минут до срока напомнить: 0, 15, 60, 1440; null — без напоминания.",
                    "type": "integer",
                    "example": 15
                },
                "repeat": {
                    "$ref": "#/definitions/internal_features_tasks_transport_http.RepeatDTO"
                },
                "title": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "internal_features_tasks_transport_http.TaskItemDTOResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "done": {
                    "type": "boolean",
                    "example": false
                },
                "id": {
                    "type": "integer",
                    "example": 12
                },
                "position": {
                    "type": "integer",
                    "example": 1
                },
                "task_id": {
                    "type": "integer",
                    "example": 5
                },
                "title": {
                    "type": "string",
                    "example": "Молоко"
                },
                "version": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_features_users_transport_http.CreateUserRequest": {
            "type": "object",
            "required": [
                "full_name"
            ],
            "properties": {
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "Ivan Ivanov"
                },
                "phone_number": {
                    "type": "string",
                    "maxLength": 15,
                    "minLength": 10,
                    "example": "+79998887766"
                }
            }
        },
        "internal_features_users_transport_http.CreateUserResponse": {
            "type": "object",
            "properties": {
                "digest_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "digest_time": {
                    "type": "string",
                    "example": "08:30"
                },
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "remind_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "telegram_id": {
                    "type": "integer",
                    "example": 123456789
                },
                "timezone": {
                    "type": "string",
                    "example": "Europe/Moscow"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.GetMeResponse": {
            "type": "object",
            "properties": {
                "digest_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "digest_time": {
                    "type": "string",
                    "example": "08:30"
                },
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "is_admin": {
                    "type": "boolean",
                    "example": false
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "remind_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "telegram_id": {
                    "type": "integer",
                    "example": 123456789
                },
                "timezone": {
                    "type": "string",
                    "example": "Europe/Moscow"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.GetUserResponse": {
            "type": "object",
            "properties": {
                "digest_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "digest_time": {
                    "type": "string",
                    "example": "08:30"
                },
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "remind_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "telegram_id": {
                    "type": "integer",
                    "example": 123456789
                },
                "timezone": {
                    "type": "string",
                    "example": "Europe/Moscow"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.PatchUserRequest": {
            "type": "object",
            "properties": {
                "digest_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "digest_time": {
                    "type": "string",
                    "example": "08:30"
                },
                "full_name": {
                    "type": "string",
                    "example": "Максим Максимович"
                },
                "phone_number": {
                    "type": "string",
                    "example": "+71112223344"
                },
                "remind_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "timezone": {
                    "type": "string",
                    "example": "Europe/Moscow"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.PatchUserResponse": {
            "type": "object",
            "properties": {
                "digest_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "digest_time": {
                    "type": "string",
                    "example": "08:30"
                },
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "remind_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "telegram_id": {
                    "type": "integer",
                    "example": 123456789
                },
                "timezone": {
                    "type": "string",
                    "example": "Europe/Moscow"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_features_users_transport_http.UserDTOResponse": {
            "type": "object",
            "properties": {
                "digest_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "digest_time": {
                    "type": "string",
                    "example": "08:30"
                },
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "id": {
                    "type": "integer",
                    "example": 10
                },
                "phone_number": {
                    "type": "string",
                    "example": "+79998887766"
                },
                "remind_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "telegram_id": {
                    "type": "integer",
                    "example": 123456789
                },
                "timezone": {
                    "type": "string",
                    "example": "Europe/Moscow"
                },
                "version": {
                    "type": "integer",
                    "example": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "TelegramInitData": {
            "description": "\"tma \u003cinitData\u003e\" из Telegram.WebApp.initData. На локальном адресе (AUTH_LOCAL_ADDR) не требуется",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Golang Todo API",
	Description:      "Todo Application REST-API scheme",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
